### ISSUE TITLE
thank  you

### ISSUE THREAD

**Issue by alzamer2** [CloudMax94/crunchyroll-cli#4]
thamks man you help me out in that batch code

and so i wanted to help you out
while i was testing and trying deffrant thing i came upon this link
http://api-manga.crunchyroll.com/cr_start_session
this for manga app but you can use it for starting anime season too
the good thing that it will always give you us sess_id so there is no regein block , here example 
http://api-manga.crunchyroll.com/cr_start_session?device_id=h&api_ver=1.0&device_type=com.crunchyroll.iphone&access_token=QWjz212GspMHH9h&version=2313.8

and yes it can take auth parameter too

**Comment by CloudMax94** [comment]
No clue how I had missed out on the fact that the manga api completely ignores your IP and uses a static (US) one to determine region. I added the ability to force US sessions in 4bc9956

**Comment by alzamer2** [comment]
you are welcome
just side note, someone point to me that my code was not working with some anime like 
[Anonymous Noise](http://www.crunchyroll.com/anonymous-noise)
after some looking and research i found out that the anime is for north of Europe like UK and Ireland 
i was able to fix the problem by using proxy from the "requests" function to create sess_id in UK
like this:
session.post('http://api.crunchyroll.com/start_session.0.json', proxies={'http': '109.169.6.152:8080'}, data=params)
i got 109.169.6.152:8080 fom the site http://free-proxy-list.net/uk-proxy.html
i hope this info will be helpfull to your code too

ps: the way i found out that Anonymous Noise is only have accses in north of Europe is by entering its [RSS](http://www.crunchyroll.com/anonymous-noise.rss) and checked which country they allow
